name: Build and release

on:
  push:
    branches: [ master ]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  release:
    name: Release ipk to GitHub Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: View content
        run: ls -R

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create master push pre-release
        if: ${{ env.RELEASE_VERSION == 'master' }}
        id: create_pre_release
        uses: ncipollo/release-action@v1
        with:
          tag: push-run-${{ github.run_number }}
          name: push-run-${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          artifacts: ./*/*.ipk

      - name: Create tagged release
        if: ${{ env.RELEASE_VERSION != 'master' }}
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          artifacts: ./*/*.ipk

  build:
    name: Build IPK package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get GitHub Build Number (ENV)
        id: get_buildno
        run: echo "GITHUBBUILDNUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Make artifact name
        id: make_artifactname
        run: |
          ARTIFACT_NAME="EXAMPLE-IPK-BUILD-${{ github.run_number }}"
          echo "${ARTIFACT_NAME}"
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

      - name: Build ipk package
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./ipk/*.ipk
