name: Build IPK package

on:
  # Triggers the workflow on push to master (also merge)
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get GitHub Build Number (ENV)
        id: get_buildno
        run: echo "GITHUBBUILDNUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Make artifact name
        id: make_artifactname
        run: |
          ARTIFACT_NAME="EXAMPLE-IPK-BUILD-${{ github.run_number }}"
          echo "${ARTIFACT_NAME}"
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

      - name: Build ipk package
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${ARTIFACT_NAME}
          path: ./ipk/*.ipk
