name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release ipk to GitHub Releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Unzip artifact
        run: unzip${{ env.ARTIFACT_NAME }}
      - name: View content
        run: ls -R
